# gemoji db/emoji.json -> the daemon's static emoji table (see gen-emoji.sh).
. as $all
| ($all | reduce .[] as $e ([]; if (index($e.category) != null) then . else . + [$e.category] end)) as $groups
| "//! The emoji table — GENERATED, do not edit by hand.",
  "//!",
  "//! Source: github/gemoji `db/emoji.json` (MIT), regenerated by",
  "//! `tools/gen-emoji/gen-emoji.sh`. Vendored rather than fetched at build time",
  "//! (unlike the dictionaries) because it is small and the picker must work",
  "//! with no data file to find and no load to wait for.",
  "//!",
  "//! `keys` are gemoji's shortcode aliases plus its tags — the search words a",
  "//! name alone doesn't carry (\"happy\" finds 😀, whose name is \"grinning face\").",
  "",
  "/// One entry of the picker: the character itself, its CLDR name, the extra",
  "/// search words, and an index into [`GROUPS`].",
  "pub(crate) struct EmojiDef {",
  "    pub ch: &'static str,",
  "    pub name: &'static str,",
  "    pub keys: &'static str,",
  "    pub group: u8,",
  "}",
  "",
  "/// Section headings, in the order the table runs.",
  "pub(crate) const GROUPS: &[&str] = &[",
  ($groups[] | "    " + (. | @json) + ","),
  "];",
  "",
  "/// Every emoji, in gemoji's (CLDR) order — the order the grid lays out.",
  "pub(crate) static EMOJI: &[EmojiDef] = &[",
  ($all[] | . as $e
    | "    EmojiDef { ch: " + ($e.emoji | @json)
    + ", name: " + ($e.description | @json)
    + ", keys: " + ((($e.aliases // []) + ($e.tags // [])) | join(" ") | @json)
    + ", group: " + (($groups | index($e.category)) | tostring)
    + " },"),
  "];"
