[workspace]
resolver = "2"
members = [
    "crates/daemon",
    "crates/client",
    "crates/core",
    "crates/proto",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1"
thiserror = "2"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
nucleo-matcher = "0.3"
freedesktop-desktop-entry = "0.8"
freedesktop-icons = "0.4"
resvg = "0.47"
glyphon = "0.8"
libc = "0.2"
serde_json = "1"

waverunner-core = { path = "crates/core" }
waverunner-proto = { path = "crates/proto" }

[profile.release]
lto = "thin"
strip = true
