# /etc/nixos/waverunner-apply.nix
#
# Privileged apply helper for waverunner's declarative installs.
#
# SECURITY MODEL
# --------------
# The ONLY user-writable surface is the DATA file
#   /home/max/.config/waverunner/packages.list   (one nixpkgs attr per line)
# This script (root) PARSES that file as data — it never `import`s it — and
# strictly validates every line against ^[a-zA-Z0-9][a-zA-Z0-9._-]*$ before
# emitting the real Nix. So a user can never smuggle a Nix expression (an
# activation script, a malicious postInstall, an `import /tmp/evil.nix`) into
# a root rebuild. The generated file below is root-owned; nothing but this
# service writes it.
#
# TRIGGER: a systemd.path watches packages.list; writing it runs this once.
# FEEDBACK: result is written to apply-status.json (chowned back to the user).
# ATOMIC: a failed `nixos-rebuild switch` never activates, and we restore the
# last-good generated file so the system always stays buildable.

{ config, pkgs, lib, ... }:

let
  user = "max";
  userHome = "/home/${user}";
  listFile = "${userHome}/.config/waverunner/packages.list";
  statusFile = "${userHome}/.config/waverunner/apply-status.json";
  generated = "/etc/nixos/waverunner-packages.nix";
  # The exact nixos-rebuild + NIX_PATH this system evaluates with, so the
  # service rebuilds against the same channel a manual rebuild would.
  nixPath = lib.concatStringsSep ":" config.nix.nixPath;

  applyScript = pkgs.writeShellApplication {
    name = "waverunner-apply";
    # This script does its own error handling (it must always write a status
    # and restore the last-good file on a failed rebuild), so drop the
    # default `errexit` — keep nounset + pipefail.
    bashOptions = [ "nounset" "pipefail" ];
    runtimeInputs = [
      config.system.build.nixos-rebuild
      config.nix.package
      pkgs.jq
      pkgs.coreutils
    ];
    text = ''
      export NIX_PATH=${lib.escapeShellArg nixPath}

      list=${lib.escapeShellArg listFile}
      status=${lib.escapeShellArg statusFile}
      gen=${lib.escapeShellArg generated}
      lastgood="$gen.last-good"
      started=$(date +%s.%N)

      write_status() {
        # $1 phase ("building"|"done")   $2 ok (true|false|null)   $3 error (json string or null)
        tmp=$(mktemp)
        printf '{"phase":"%s","ok":%s,"started":%s,"finished":%s,"error":%s}\n' \
          "$1" "$2" "$started" "$(date +%s.%N)" "$3" > "$tmp"
        mv "$tmp" "$status"
        chown ${user}:users "$status" 2>/dev/null || true
        chmod 644 "$status" 2>/dev/null || true
      }

      write_status "building" null null

      # 1. Validate: keep only strict nixpkgs attr tokens; anything else is
      #    dropped (never interpreted).
      attrs=()
      if [[ -f "$list" ]]; then
        while IFS= read -r line || [[ -n "$line" ]]; do
          line="''${line%%#*}"
          line="$(printf '%s' "$line" | tr -d '[:space:]')"
          if [[ -z "$line" ]]; then
            continue
          fi
          if [[ "$line" =~ ^[a-zA-Z0-9][a-zA-Z0-9._-]*$ ]]; then
            attrs+=("$line")
          else
            echo "waverunner-apply: rejected invalid entry: $line" >&2
          fi
        done < "$list"
      fi

      # 2. Generate the root-owned Nix from the validated tokens.
      {
        echo "# Generated by waverunner-apply from packages.list. Do not edit by hand."
        echo "{ pkgs, ... }:"
        echo "{"
        echo "  home.packages = with pkgs; ["
        for a in ''${attrs[@]+"''${attrs[@]}"}; do
          echo "    $a"
        done
        echo "  ];"
        echo "}"
      } > "$gen.new"
      mv "$gen.new" "$gen"

      # 3. Rebuild. On success snapshot last-good; on failure restore it so
      #    the next rebuild (e.g. autoUpgrade) is never poisoned by a bad add.
      if err=$(nixos-rebuild switch 2>&1); then
        cp -f "$gen" "$lastgood"
        write_status "done" true null
      else
        if [[ -f "$lastgood" ]]; then
          cp -f "$lastgood" "$gen"
        fi
        errjson=$(printf '%s' "$err" | tail -c 4000 | jq -Rs .)
        write_status "done" false "$errjson"
        echo "$err" >&2
        exit 1
      fi
    '';
  };
in
{
  ##### Auto-upgrade: weekly channel bump + rebuild, never auto-reboot.
  ##### (App installs use the CURRENT channel and are unaffected by this.)
  system.autoUpgrade = {
    enable = true;
    dates = "weekly";
    allowReboot = false;
  };

  ##### The apply service (root, oneshot) + the path unit that triggers it
  ##### when the user's packages.list changes.
  systemd.services.waverunner-apply = {
    description = "Apply waverunner's declarative package list (nixos-rebuild switch)";
    serviceConfig = {
      Type = "oneshot";
      ExecStart = "${applyScript}/bin/waverunner-apply";
      # One rebuild at a time.
      # (oneshot already serializes; this keeps a queued trigger tidy.)
    };
  };

  systemd.paths.waverunner-apply = {
    description = "Watch waverunner's packages.list for changes";
    wantedBy = [ "multi-user.target" ];
    pathConfig = {
      PathChanged = listFile;
      Unit = "waverunner-apply.service";
    };
  };
}
